version: '{build}'

build: off

install:
  - appveyor AddMessage -Category Information "Install metanotrma"
  - bitsadmin /transfer get https://raw.githubusercontent.com/riboseinc/metanorma-windows-setup/%APPVEYOR_REPO_COMMIT%/install.bat %cd%\install.bat & .\install.bat
  - echo "Script returned %ERRORLEVEL%"
  - appveyor AddMessage -Category Information "Install docker"
  - ps: (Invoke-WebRequest "https://raw.githubusercontent.com/riboseinc/metanorma-windows-setup/$Env:APPVEYOR_REPO_COMMIT/docker.bat" -OutFile 'docker.bat'); .\docker.bat
  - appveyor AddMessage -Category Information "Script returned %ERRORLEVEL%"
  - refreshenv

test_script:
  - git clone https://github.com/riboseinc/unece-cefact-recommendation-42.git & cd unece-cefact-recommendation-42
  - set PATH=c:\tools\ruby25\bin;%PATH%
  - gem install bundler -v 1.17.3
  - call make -f Makefile.win clean all
  - echo "Script returned %ERRORLEVEL%"

on_finish:
  - 7z a %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.zip %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42\unece-cefact-recommendation-42.*
  - 7z a %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.zip %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42\images
  - 7z a %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42.zip %APPVEYOR_BUILD_FOLDER%\unece-cefact-recommendation-42\reference-docs
  - ps: Push-AppveyorArtifact $Env:APPVEYOR_BUILD_FOLDER\metanorma_install.log
  - ps: Push-AppveyorArtifact $Env:APPVEYOR_BUILD_FOLDER\unece-cefact-recommendation-42.zip