version: '{build}'

# https://help.appveyor.com/discussions/questions/1929-create-a-docker-machine-in-appveyor-build-nested-hypervisor-needed
image: Visual Studio 2017

build: off

test_script:
  - appveyor AddMessage -Category Information "Test install script"
  - bitsadmin /transfer get https://raw.githubusercontent.com/CAMOBAP795/metanorma-windows-setup/master/install.bat %cd%\install.bat & .\install.bat
  - set exit_code=%ERRORLEVEL%
  - echo "Install script returned %exit_code%"
  - exit /B %exit_code%
  - echo "Test DONE"

artifacts:
  - path: metanorma_install.log
    name: install.log